import Head from 'next/head'
import Layout from '@/components/Layout/Layout'
import Slide from '@/components/Slide/Slide'
import AboutUs from '@/components/AboutUs/AboutUs'

export default function Home() {
  return (
    
      <Layout>
        <Head>
          <title>Blitz & Bella</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <section className='w-4/5 mx-auto border-solid border-y-black  border-4 flex mt-52'>
          <AboutUs/>
          <Slide />
        </section>
      </Layout>
  )
}
